#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "civicrm_drupal7"
name = "CiviCRM on Drupal 7"
description.en = "CRM for non-profits, NGOs and advocacy organizations"
description.fr = "CRM pour organisations à but non lucratif et ONG"

version = "5.69.4~ynh4"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://civicrm.org"
demo = "https://civicrm.org/demo"
admindoc = "https://docs.civicrm.org/"
code = "https://github.com/civicrm/civicrm-drupal"
cpe = "cpe:2.3:a:civicrm:civicrm"
fund = "https://civicrm.org/civicrm/contribute/transact?reset=1&id=47"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "460M"
ram.build = "250M"
ram.runtime = "128M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/drupal7"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.install_profil]
    ask.en = "Choose the Drupal 7 install profile to use"
    ask.fr = "Choisissez le profile d'installation de Drupal 7"
    type = "select"
    choices = ["minimal", "standard"]
    default = "standard"

[resources]

    [resources.sources]
    [resources.sources.civicrm-drupal]
    url = "https://download.civicrm.org/civicrm-5.69.4-drupal.tar.gz"
    sha256 = "8eb452e132ac64a9f09e6151b5441e0c20682482e917586973432c8756f281b2"

    [resources.sources.civicrm-l10n]
    url = "https://download.civicrm.org/civicrm-5.69.4-l10n.tar.gz"
    sha256 = "84b537da5b8d0b54f254bc2c456ce472568ccf2aff9f3017346e9570b2efdaf9"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php8.2-fpm",
        "php8.2-cli",
        "php8.2-gd",
        "php8.2-mysql",
        "php8.2-xml",
        "php8.2-ldap",
        "php8.2-mbstring",
        "php8.2-uploadprogress",
        "php8.2-apcu",
        "php8.2-curl",
        "php8.2-soap",
        "php8.2-intl",
        "curl",
        "libzip-dev",
        "mariadb-server",
        ]

    [resources.database]
    type = "mysql"
