#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.install_profil = "standard"
    args.language = "fr"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.e5263194b69560d48338fe94d111afb460b047ee.name = "5.52.2~ynh1"
    test_upgrade_from.878de5bcc469b0b4493497232d02256aaca3135d.name = "5.69.4~ynh2"
    test_upgrade_from.1a0530fe84f216b69dd8d9469a7b425cf59833ab.name = "5.69.4~ynh3"
