#!/bin/bash

action=$1
pending_dir=$4
mysqlconf="${pending_dir}/../mysql/etc/mysql/my.cnf"

[[ "$action" == "pre" ]] || exit 0
[[ -e "$mysqlconf" ]] || exit 0

sed --in-place "s@thread_stack = 128K@thread_stack = 192K@g" "${mysqlconf}"