#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

ynh_app_setting_set --key=php_upload_max_filesize --value=512M
ynh_app_setting_set --key=php_post_max_size --value=512M
ynh_app_setting_set --key=php_memory_limit --value=512M

#=================================================
# INSTALL COMPOSER
#=================================================
ynh_script_progression "Installing Composer..."

composer_workdir="$install_dir/.composer"
install -d -m 750 -o $app -g $app $composer_workdir
ynh_config_add --template="composer.json" --destination="$composer_workdir/composer.json"

ynh_composer_install
ynh_composer_exec install --no-dev

#=================================================
# CREATE DRUSH ALIAS
#=================================================
ynh_script_progression "Creating Drush alias..."

install -d -m 750 -o $app -g $app "$install_dir/.drush"
ynh_config_add --template="yoursite.aliases.drushrc.php" --destination="$install_dir/.drush/$app.aliases.drushrc.php"

#=================================================
# INSTALL DRUPAL AND CIVICRM
#=================================================
ynh_script_progression "Installing Drupal and CiviCRM..."

update-alternatives --set php /usr/bin/php$php_version

pushd "$install_dir"
	_ynh_exec_with_drush_php drush pm-download -y drupal-7 --drupal-project-rename=web

	_ynh_exec_with_drush_php drush "@$app" site:install "$install_profil" \
		--account-name="$admin" \
		--account-pass="$password" \
		--account-mail="$admin_mail" \
		--db-url="mysql://$db_user:$db_pwd@localhost/$db_name" \
		--site-name="$app" \
		--locale="$language" \
		--yes

	echo "\$conf['trusted_host_patterns'] = ['^$domain\$'];" >> "$install_dir/web/sites/default/settings.php"

	install -d -m 770 -o $app -g www-data "$install_dir/tmp"
	ynh_config_add --template=".htaccess" --destination="$install_dir/tmp/.htaccess"
	chmod 0444 "$install_dir/tmp/.htaccess"
	echo "\$conf['file_temporary_path'] = '../tmp';" >> "$install_dir/web/sites/default/settings.php"

	install -d -m 770 -o $app -g www-data "$install_dir/private"
	ynh_config_add --template=".htaccess" --destination="$install_dir/private/.htaccess"
	chmod 0444 "$install_dir/private/.htaccess"
	echo "\$conf['file_private_path'] = '../private';" >> "$install_dir/web/sites/default/settings.php"

	_ynh_exec_with_drush_php drush "@$app" pm-download drush_language
	# _ynh_exec_with_drush_php drush "@$app" pm-download ldap
	# _ynh_exec_with_drush_php drush "@$app" pm-enable -y ldap_servers ldap_user ldap_authentication ldap_authorization ldap_authorization_drupal_role
	_ynh_exec_with_drush_php drush "@$app" pm-download l10n_update
	_ynh_exec_with_drush_php drush "@$app" pm-enable -y l10n_update
	_ynh_exec_with_drush_php drush "@$app" language-add "$language"
	_ynh_exec_with_drush_php drush "@$app" language-default "$language"
	_ynh_exec_with_drush_php drush "@$app" cache-clear drush
	_ynh_exec_with_drush_php drush "@$app" l10n-update-refresh
	_ynh_exec_with_drush_php drush "@$app" l10n-update
	_ynh_exec_with_drush_php drush "@$app" pm-update
	_ynh_exec_with_drush_php drush "@$app" core-cron

	ynh_setup_source --dest_dir="$install_dir/web/sites/all/modules/civicrm" --source_id="civicrm-drupal"
	ynh_setup_source --dest_dir="$install_dir/web/sites/all/modules/civicrm" --source_id="civicrm-l10n"

	touch "$install_dir/web/sites/default/civicrm.settings.php"
	chmod 644 "$install_dir/web/sites/default/civicrm.settings.php"
	chown "$app:www-data" "$install_dir/web/sites/default/civicrm.settings.php"

	_ynh_exec_with_drush_php drush --include="$install_dir/web/sites/all/modules/civicrm/drupal/drush" "@$app" civicrm-install \
		--dbhost="localhost" --dbname="$db_name" --dbpass="$db_pwd" --dbuser="$db_user" --destination="sites/all/modules" --site_url="$domain$path" --ssl=on
popd

ynh_store_file_checksum "$install_dir/web/sites/default/settings.php"
ynh_store_file_checksum "$install_dir/web/sites/default/civicrm.settings.php"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
