#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=php_upload_max_filesize --value=512M
ynh_app_setting_set_default --key=php_post_max_size --value=512M
ynh_app_setting_set_default --key=php_memory_limit --value=512M

if [ -d "$install_dir/$app" ]; then
  mv "$install_dir/$app" "$install_dir/web"
fi

#=================================================
# UPGRADE COMPOSER
#=================================================
ynh_script_progression "Upgrading Composer..."

composer_workdir="$install_dir/.composer"
install -d -m 750 -o $app -g $app $composer_workdir
ynh_config_add --template="composer.json" --destination="$composer_workdir/composer.json"

ynh_composer_install
ynh_composer_exec install --no-dev

#=================================================
# CREATE DRUSH ALIAS
#=================================================
ynh_script_progression "Creating Drush alias..."

install -d -m 750 -o $app -g $app "$install_dir/.drush"
ynh_config_add --template="yoursite.aliases.drushrc.php" --destination="$install_dir/.drush/$app.aliases.drushrc.php"

#=================================================
# UPGRADE DRUPAL
#=================================================
ynh_script_progression "Upgrading Drupal..."

ynh_backup_if_checksum_is_different "$install_dir/web/sites/default/settings.php"
ynh_backup_if_checksum_is_different "$install_dir/web/sites/default/civicrm.settings.php"

update-alternatives --set php /usr/bin/php$php_version

pushd "$install_dir"
	_ynh_exec_with_drush_php drush "@$app" variable-set --exact maintenance_mode 1
	_ynh_exec_with_drush_php drush "@$app" cache-clear all
	_ynh_exec_with_drush_php drush "@$app" pm-update -y drupal
	_ynh_exec_with_drush_php drush "@$app" cache-clear all
	_ynh_exec_with_drush_php drush "@$app" l10n-update-refresh
	_ynh_exec_with_drush_php drush "@$app" l10n-update
	ynh_setup_source --dest_dir="$install_dir/web/sites/all/modules/civicrm" --source_id="civicrm-drupal" --full_replace
	ynh_setup_source --dest_dir="$install_dir/web/sites/all/modules/civicrm" --source_id="civicrm-l10n"

	_ynh_exec_with_drush_php drush --include="$install_dir/web/sites/all/modules/civicrm/drupal/drush" "@$app" -y civicrm-upgrade-db

	_ynh_exec_with_drush_php drush "@$app" variable-set --exact maintenance_mode 0
popd

ynh_store_file_checksum "$install_dir/web/sites/default/settings.php"
ynh_store_file_checksum "$install_dir/web/sites/default/civicrm.settings.php"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
